name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Explicitly grant the workflow permission to write repository contents
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build (static export)
        run: npm run export

      - name: Show generated files (debug)
        run: |
          echo "PWD: $(pwd)"
          echo "Listing repo root:"; ls -la
          echo "Listing out/ (if present):"; ls -la out || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
